export const FETCH_OWNERS_START = 'FETCH_OWNERS_START';
export const FETCH_OWNERS_SUCCESS = 'FETCH_OWNERS_SUCCESS';
export const FETCH_ACTIVE_PATIENTS_START = 'FETCH_ACTIVE_PATIENTS_START';
export const FETCH_ACTIVE_PATIENTS_SUCCESS = 'FETCH_ACTIVE_PATIENTS_SUCCESS';
