export const FETCH_OWNERS_START = 'FETCH_OWNERS_START';
export const FETCH_OWNERS_SUCCESS = 'FETCH_OWNERS_SUCCESS';
export const FETCH_OWNER_START = 'FETCH_OWNER_START';
export const FETCH_OWNER_SUCCESS = 'FETCH_OWNER_SUCCESS';
export const UPDATE_OWNER_START = 'UPDATE_OWNER_START';
export const UPDATE_OWNER_SUCCESS = 'UPDATE_OWNER_SUCCESS';

export const FETCH_ACTIVE_PATIENTS_START = 'FETCH_ACTIVE_PATIENTS_START';
export const FETCH_ACTIVE_PATIENTS_SUCCESS = 'FETCH_ACTIVE_PATIENTS_SUCCESS';
export const FETCH_PATIENT_START = 'FETCH_PATIENT_START';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
